// Automatically generated by make_root_pointers.py.

const char *readline_hist[(8)];
mp_obj_list_t mp_sys_argv_obj;
mp_obj_list_t mp_sys_path_obj;
mp_obj_t sys_mutable[MP_SYS_MUTABLE_NUM];
mp_obj_t track_reloc_code_list;
mp_sched_item_t sched_queue[(8)];
struct _mp_vfs_mount_t *vfs_cur;
struct _mp_vfs_mount_t *vfs_mount_table;
void *machine_i2s_obj[2];
void *machine_pin_irq_obj[30];
void *rp2_pio_irq_obj[2];
void *rp2_state_machine_irq_obj[8];
void *rp2_uart_rx_buffer[2];
void *rp2_uart_tx_buffer[2];
